version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: fotoland-db
    environment:
      POSTGRES_DB: fotolanddb
      POSTGRES_USER: fotolanduser
      POSTGRES_PASSWORD: fotolandpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
